"""remove hhhh

Revision ID: 1ce29d2e7e54
Revises: d4c539aeb70c
Create Date: 2025-01-09 20:41:37.128463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce29d2e7e54'
down_revision: Union[str, None] = 'd4c539aeb70c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pokemons_id'), 'pokemons', ['id'], unique=False)
    op.drop_column('pokemons', 'hhhh')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.add_column('pokemons', sa.Column('hhhh', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_pokemons_id'), table_name='pokemons')
    # ### end Alembic commands ###
