"""Add image_url to Pokemon model

Revision ID: 254c52f4df95
Revises: 59295ca21990
Create Date: 2025-01-16 17:17:51.371764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '254c52f4df95'
down_revision: Union[str, None] = '59295ca21990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pokemons', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pokemons', 'pokemon_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pokemons', 'abilities',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    op.alter_column('pokemons', 'stats',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    op.alter_column('pokemons', 'types',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    op.create_index(op.f('ix_pokemons_name'), 'pokemons', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokemons_name'), table_name='pokemons')
    op.alter_column('pokemons', 'types',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('pokemons', 'stats',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('pokemons', 'abilities',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('pokemons', 'pokemon_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pokemons', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
